config_id: "scenario_observation_baseline"
seed: 8080

features:
  stages:
    relationships: "B"
    social_rewards: "OFF"
  systems:
    lifecycle: "on"
    observations: "hybrid"
  training:
    curiosity: "off"
  console:
    mode: "viewer"

world:
  grid_size: [24, 24]
  weather_seed: 909

rewards:
  needs_weights:
    hunger: 1.0
    hygiene: 0.5
    energy: 0.6
  decay_rates:
    hunger: 0.0
    hygiene: 0.0
    energy: 0.0
  survival_tick: 0.0
  punctuality_bonus: 0.0
  wage_rate: 0.0
  faint_penalty: -1.0
  eviction_penalty: -2.0

behavior:
  hunger_threshold: 0.2
  hygiene_threshold: 0.2
  energy_threshold: 0.2
  job_arrival_buffer: 5

queue_fairness:
  cooldown_ticks: 10
  ghost_step_after: 1
  age_priority_weight: 0.0

conflict:
  rivalry:
    increment_per_conflict: 0.0
    decay_per_tick: 0.1
    avoid_threshold: 1.0
    max_edges: 1

scenario:
  description: "Single agent idle baseline—provides control replay sample with zero rewards and stable observations."
  ticks: 20
  agents:
    - id: iris
      position: [12, 12]
      needs: {hunger: 0.4, hygiene: 0.4, energy: 0.4}
      wallet: 1.0
      schedule:
        - {kind: wait, object: null, affordance: null, blocked: false}
