
config_id: "scenario_queue_conflict"
seed: 5252

features:
  stages:
    relationships: "B"
    social_rewards: "OFF"
  systems:
    lifecycle: "on"
    observations: "hybrid"
  training:
    curiosity: "off"
  console:
    mode: "viewer"

world:
  grid_size: [24, 24]
  weather_seed: 2025

rewards:
  needs_weights:
    hunger: 1.0
    hygiene: 0.5
    energy: 0.6
  decay_rates:
    hunger: 0.0
    hygiene: 0.0
    energy: 0.0
  survival_tick: 0.0
  punctuality_bonus: 0.0
  wage_rate: 0.0
  faint_penalty: -1.0
  eviction_penalty: -2.0

behavior:
  hunger_threshold: 0.2
  hygiene_threshold: 0.2
  energy_threshold: 0.2
  job_arrival_buffer: 5

queue_fairness:
  cooldown_ticks: 4
  ghost_step_after: 1
  age_priority_weight: 0.0

conflict:
  rivalry:
    increment_per_conflict: 0.2
    decay_per_tick: 0.01
    avoid_threshold: 0.4
    max_edges: 4

scenario:
  description: "Three agents contest a single shower, forcing ghost-steps and rotation cooldowns."
  ticks: 80
  objects:
    - id: shower_conflict
      type: shower
      position: [12, 12]
  agents:
    - id: anna
      position: [10, 12]
      needs: {hunger: 0.6, hygiene: 0.2, energy: 0.6}
      wallet: 2.0
      schedule:
        - {kind: move, position: [12, 12], blocked: false}
        - {kind: request, object: shower_conflict, affordance: use_shower, blocked: false}
        - {kind: start, object: shower_conflict, affordance: use_shower, blocked: false}
        - {kind: wait, object: null, affordance: null, blocked: false}
        - {kind: release, object: shower_conflict}
        - {kind: wait, object: null, affordance: null, blocked: false}
    - id: ben
      position: [14, 12]
      needs: {hunger: 0.6, hygiene: 0.3, energy: 0.6}
      wallet: 2.0
      schedule:
        - {kind: move, position: [13, 12], blocked: false}
        - {kind: request, object: shower_conflict, affordance: use_shower, blocked: true}
        - {kind: blocked, object: shower_conflict, blocked: true}
        - {kind: request, object: shower_conflict, affordance: use_shower, blocked: false}
        - {kind: start, object: shower_conflict, affordance: use_shower, blocked: false}
        - {kind: release, object: shower_conflict}
        - {kind: wait, object: null, affordance: null, blocked: false}
    - id: cara
      position: [12, 14]
      needs: {hunger: 0.6, hygiene: 0.25, energy: 0.6}
      wallet: 2.0
      schedule:
        - {kind: move, position: [12, 13], blocked: false}
        - {kind: request, object: shower_conflict, affordance: use_shower, blocked: true}
        - {kind: blocked, object: shower_conflict, blocked: true}
        - {kind: request, object: shower_conflict, affordance: use_shower, blocked: false}
        - {kind: start, object: shower_conflict, affordance: use_shower, blocked: false}
        - {kind: release, object: shower_conflict}
        - {kind: wait, object: null, affordance: null, blocked: false}
