apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "townlet-web.fullname" . }}-gateway
  labels:
    app: {{ include "townlet-web.name" . }}
    component: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "townlet-web.name" . }}
      component: gateway
  template:
    metadata:
      labels:
        app: {{ include "townlet-web.name" . }}
        component: gateway
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value in .Values.gateway.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources: {{ toYaml .Values.gateway.resources | nindent 12 }}
