- type: object
  id: shower_1
  object_type: shower
- type: object
  id: bed_1
  object_type: bed

- id: use_shower
  object_type: shower
  preconds:
    - "occupied == false"
    - "power_on == true"
  duration: 30
  effects:
    hygiene: 0.45
    energy: -0.03
    money: -0.2
  hooks:
    before: ["on_attempt_shower"]
    after: ["on_finish_shower"]
    fail: ["on_no_power"]
- type: object
  id: fridge_1
  object_type: fridge

- id: eat_meal
  object_type: fridge
  preconds:
    - "meal_available == true"
  duration: 15
  effects:
    hunger: 0.4
    energy: 0.05
    money: -0.4
  hooks:
    before: ["on_attempt_eat"]
    after: ["on_finish_eat"]
- id: cook_meal
  object_type: stove
  duration: 40
  effects:
    hunger: 0.1
    energy: -0.05
  hooks:
    before: ["on_attempt_cook"]
    after: ["on_finish_cook"]
    fail: ["on_cook_fail"]
- id: rest_sleep
  object_type: bed
  duration: 60
  effects:
    energy: 0.8
  hooks:
    before: ["on_attempt_sleep"]
    after: ["on_finish_sleep"]
