- type: object
  id: shower_1
  object_type: shower

- id: use_shower
  object_type: shower
  preconds:
    - "occupied == false"
    - "power_on == true"
  duration: 30
  effects:
    hygiene: 0.45
    energy: -0.03
    money: -0.2
  hooks:
    before: ["on_attempt_shower"]
    after: ["on_finish_shower"]
    fail: ["on_no_power"]
- type: object
  id: fridge_1
  object_type: fridge

- id: eat_meal
  object_type: fridge
  preconds:
    - "meal_available == true"
  duration: 15
  effects:
    hunger: 0.4
    energy: 0.05
    money: -0.4
  hooks:
    before: ["on_attempt_eat"]
    after: ["on_finish_eat"]
