name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check src tests
          mypy src
      - name: Unit tests
        run: pytest -k "not rollout_capture"

      - name: Rollout scenario tests
        run: pytest tests/test_rollout_capture.py
