name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check src tests
          mypy src
      - name: Unit tests
        run: pytest -k "not rollout_capture"

      - name: Telemetry schema tests
        run: pytest tests/test_training_replay.py::test_training_harness_ppo_conflict_telemetry

      - name: PPO telemetry validator
        run: |
          python scripts/validate_ppo_telemetry.py docs/samples/ppo_conflict_telemetry.jsonl

      - name: Mixed-mode rollout validation
        run: |
          python scripts/capture_rollout.py configs/scenarios/queue_conflict.yaml --output tmp/ci_phase4
          python scripts/run_training.py configs/scenarios/queue_conflict.yaml --mode mixed --replay-manifest tmp/ci_phase4/rollout_sample_manifest.json --rollout-ticks 40 --epochs 1 --ppo-log tmp/ci_phase4/ppo_mixed.jsonl
          python scripts/validate_ppo_telemetry.py tmp/ci_phase4/ppo_mixed.jsonl
          python scripts/validate_ppo_telemetry.py tmp/ci_phase4/ppo_mixed.jsonl --baseline <(head -n 1 tmp/ci_phase4/ppo_mixed.jsonl)
          python scripts/telemetry_watch.py tmp/ci_phase4/ppo_mixed.jsonl --kl-threshold 0.5 --grad-threshold 5 --entropy-threshold -0.2 --reward-corr-threshold -0.5
          python scripts/telemetry_summary.py tmp/ci_phase4/ppo_mixed.jsonl --format markdown > tmp/ci_phase4/summary.md

      - name: Rollout scenario tests
        run: pytest tests/test_rollout_capture.py
